name: Deploy to Heroku (Server)

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/server.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add server remote origin
        run: git remote add heroku-server https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_BACKEND_APP_NAME }}.git
      - name: Deploy server to Heroku
        run: git push heroku-server `git subtree split --prefix server main`:refs/heads/main --force
